export const courseData = [
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: null,
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: "956",
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "lorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem lorem",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: null,
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: null,
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: null,
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: "800",
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: null,
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: null,
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: "735",
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: null,
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: null,
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: null,
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: null,
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: null,
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: null,
  },
  {
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: "535",
    orgPrice: null,
  },
];
