export const courseData = [
  {
    tag: 1,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 2,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: 956,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 3,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name:
      "lorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem loremlorem lorem",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 4,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 5,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 6,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: 800,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 7,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 8,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 9,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: 735,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 10,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 11,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 12,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 13,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 14,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 15,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
  {
    tag: 16,
    courseIMG: "https://m.media-amazon.com/images/I/41gr3r3FSWL.jpg",
    name: "Book cover Design Formula",
    author: "Anita Nipane",
    disPrice: 535,
    orgPrice: null,
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsum sint suscipit natus similique unde, maxime aspernatur enim veniam reprehenderit doloremque, necessitatibus blanditiis odio tempore quia cumque debitis quisquam! Nesciunt quasi optio alias laborum debitis asperiores, fugit iste obcaecati laudantium nostrum id cupiditate veniam voluptas error totam dicta ea odio ipsum perspiciatis. Sit beatae mollitia amet minus reiciendis. Quis, velit distinctio obcaecati saepe optio similique nisi error fuga`,
  },
];
